apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:9
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 1024Mi
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@intility.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: admin
            - name: PGADMIN_LISTEN_PORT
              value: "5050"
          ports:
            - name: http
              containerPort: 5050
              protocol: TCP
          volumeMounts:
            - name: servers-config-volume
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
              readOnly: true
            - name: system-config-volume
              mountPath: /etc/pgadmin/config_system.py
              subPath: config_system.py
              readOnly: true
            - name: pgadmin-data
              mountPath: /var/lib/pgadmin
      volumes:
        - name: servers-config-volume
          configMap:
            name: pgadmin-servers-config
        - name: system-config-volume
          configMap:
            name: pgadmin-system-config
        - name: pgadmin-data
          persistentVolumeClaim:
            claimName: pgadmin-data-pvc
