apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - backup.yaml
  - db-admin.secret.yaml
  - db-user.secret.yaml
  - cluster.yaml
  - ro.pooler.yaml
  - rw.pooler.yaml
  - secret-store.yaml
  - podmonitor.yaml
  - backup.objectstore.yaml
  - restore.objectstore.yaml
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: replace-pg-namespace-transformer
      namespace: replace-pg-cluster
    unsetOnly: true
generatorOptions:
  disableNameSuffixHash: true
