apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - backup.secret.yaml
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: workshop-pg-namespace-transformer
      namespace: workshop-pg-cluster
    unsetOnly: true
generatorOptions:
  disableNameSuffixHash: true
